### ISSUE TITLE
Link ci/code-climate with repo

### ISSUE THREAD

**Issue by ystamaritq** [Holiday-Secret-Santa/Secret-Santa-App#6]
### To Do Items for this Issue
- [x] Link code-climate with repo
- [x] Link to circleci
- [x] debug test to work correctly 

### Summary of Error
I continue to get an error message when the circleci build finishes for each github push. It appears that the build is erroring out because it does not recognize a coverage folder/files. However, when we run `npm run test` locally, we confirm that the coverage folder and files do exist in the root and client directories. I added the following screenshots for reference to help debug this issue:

- Current error message in circleci
- Repo folder screenshot
- Config.yml file
- Root package.json
- Client package.json

#### Current error message in circleci
![image](https://user-images.githubusercontent.com/58799056/92318765-9b8d7400-efd6-11ea-9371-886dfdd83631.png)

#### Repo folder screenshot
![image](https://user-images.githubusercontent.com/58799056/92332524-22c50100-f044-11ea-8548-f093eba5012f.png)

#### Config.yml file
![image](https://user-images.githubusercontent.com/58799056/92332621-ef36a680-f044-11ea-8fd9-498395dfceeb.png)

#### Root package.json
![image](https://user-images.githubusercontent.com/58799056/92332633-08d7ee00-f045-11ea-8f6e-882b14036ece.png)

#### Client package.json
![image](https://user-images.githubusercontent.com/58799056/92332648-17bea080-f045-11ea-8b9c-826ab8b02303.png)

**Comment by KEDuran** [comment]
I reopened this issue because the circleci configuration continues to not yield a passing sample test. Issues may be related to dependencies in the package.json. More reserved needed. Here is the error message I get in circleci

![image.png](https://user-images.githubusercontent.com/58799056/92317960-cde5a400-efcb-11ea-9c79-0872cb458221.png)

**Comment by KEDuran** [comment]
I was able to get circleci configs to showing passing tests. However, we still have an error related to the coverage file. I took a screenshot of the error populating in the circleci build. 

![image](https://user-images.githubusercontent.com/58799056/92318506-f329e080-efd2-11ea-8fd2-073b2d889356.png)

**Comment by antoniojgage** [comment]
Looks like your backend script needs to create a coverage report. Prior we were only testing the react frontend, you'll need to make sure the same script from the package.json runs tests for both frontend & backend then generates a coverage report

https://github.com/Holiday-Secret-Santa/Secret-Santa-App/blob/0ab85445929b315c9a35bc8769b98d0202007791/package.json#L15

**Comment by antoniojgage** [comment]
If you're using mocha you'll need to look up this. But remember since your backend needs to run your frontend it needs to run the tests there also.

https://stackoverflow.com/questions/16633246/code-coverage-with-mocha

**Comment by KEDuran** [comment]
I ended up removing mocha and installing jest. I believe the mocha test command was copied in the package.json from the previous project. I added more detail and screenshots in the issue description to help show the error message from circleci and the current state of our repo in this issues description.

**Comment by KEDuran** [comment]
### Progress Update
The circleci build finally succeed. In order to get the build to succeed, I had to break out the front-end and back-end test commands in the config.yml. However, as a result, circleci is only pushing the back-end test results to code climate. The front-end tests in the client folder are not being read to code climate.  In included the following screenshot images for reference material.

- Updated config.yml file
- Circleci messages
- Code Climate report results
- Code climate dashboard results

#### Updated config.yml file
![image](https://user-images.githubusercontent.com/58799056/92334457-bce07580-f053-11ea-9b32-a10cd2557160.png)

#### Circleci messages - Backend test coverage
![image](https://user-images.githubusercontent.com/58799056/92334476-f0bb9b00-f053-11ea-922a-2fefe2fbdd4c.png)

#### Circleci messages - Front test coverage
![image](https://user-images.githubusercontent.com/58799056/92334481-fe712080-f053-11ea-8fb9-dac007b86e64.png)

#### Code Climate report results
![image](https://user-images.githubusercontent.com/58799056/92334493-1a74c200-f054-11ea-8198-b30d656ecd83.png)

#### Code climate dashboard results (refreshed before adding to issue)
![image](https://user-images.githubusercontent.com/58799056/92334505-2fe9ec00-f054-11ea-90e9-f9b01f9e2176.png)
